export const cuisineList = [
    "Italian",
    "Vegetarian",
    "Vegan",
    "Healthy",
    "Greek",
    "Japanese",
    "Brunch",
    "Thai",
    "Mexican",
    "Gluten Free",
    "Indian",
    "Organic",
    "Persian",
    "Breakfast",
    "Spanish",
    "Sandwich",
    "Pizza",
    "Salads",
    "Sushi",
    "Tacos",
    "Cantonese",
    "Lebanese",
    "Turkish",
    "Ethiopian"
]